source "https://rubygems.org"
ruby File.read("#{__dir__}/.ruby-version")

gemspec

# TODO: move this to .gemspec
gem "foobara", git: "foobara", branch: "main"

# gem "foobara-dotenv-loader", github: "foobara/dotenv-loader"
# gem "foobara-dotenv-loader", path: "../dotenv-loader"
# gem "foobara-local-files-crud-driver", github: "local-files-crud-driver", branch: "main"
# gem "foobara-local-files-crud-driver", path: "..-connector", branch: "main"
# gem "foobara-local-files-crud-driver", github: "foobara/local-files-crud-driver"
# gem "foobara-local-files-crud-driver", path: "../local-files-crud-driver"
# gem "foobara-local-files-crud-driver", github: "foobara/local-files-crud-driver"
# gem "foobara-local-files-crud-driver", path: "../local-files-crud-driver"
# gem "foobara-local-files-crud-driver", github: "foobara/local-files-crud-driver"
# gem "foobara-local-files-crud-driver", path: "../local-files-crud-driver"
# gem "foobara-local-files-crud-driver", github: "foobara/local-files-crud-driver"
# gem "foobara-sh-cli-connector", path: "../sh-cli-connector"
gem "foobara-util", github: "foobara/util"
# gem "foobara-util", path: "../util"

gem "rake"

group :development do
  gem "foob"
  gem "foobara-command-generator"
  gem "foobara-domain-generator"
  gem "foobara-empty-ruby-project-generator"
  gem "foobara-files-generator"
  gem "foobara-organization-generator"
  gem "foobara-rubocop-rules"
  gem "guard-rspec"
  gem "rubocop-rake"
  gem "rubocop-rspec"
end

group :development, :test do
  gem "pry"
  gem "pry-byebug"
end

group :test do
  gem "foobara-spec-helpers"
  gem "rspec"
  gem "rspec-its"
  gem "simplecov"
end
